CodeIntelligenceTesting/jazzer

- WORKSPACE.bazel
- maven_install.json
Google's Maven repository does not offer most of our dependencies, which
makes Bazel print quite a few warnings while downloading.
> Remove Google Maven repo

- README.md
- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/runtime/ManifestUtils.kt
- bazel/fuzz_target.bzl
- driver/fuzz_target_runner.cpp
- driver/fuzz_target_runner.h
By reading the fuzz target class from a JAR manifest entry rather than
a command-line argument, fuzz targets can be fully self-contained.
This commit adds a Java function that looks for a unique
`Fuzz-Target-Class` attribute in all manifests on the classpath and
returns it to the driver if found. If no such entry is found, it
falls back to the `--target_class` commandline parameter.
> Optionally read fuzz target class from JAR manifest

- driver/signal_handler.cpp
The handleInterrupt native callback should take JNIEnv and jclass as
arguments.
> Fix handleInterrupt signature

- BUILD.bazel
- WORKSPACE.bazel
- agent/src/main/java/com/code_intelligence/jazzer/api/BUILD.bazel
- jazzer-api.pom
- maven.bzl
The uploaded jar previously did not contain any class files and lacked
required POM fields.
> Fix Bazel rules for Maven publishing

- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/EdgeCoverageInstrumentor.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/CoverageInstrumentationTest.kt
According to
https://www.usenix.org/system/files/woot20-paper-fioraldi.pdf,
letting coverage 8-bit counters wrap from 255 to 1 on increment performs
better than having them stay at 255. In fact, the latter has been
observed to hurt overall coverage.
> Use NeverZero instead of Saturated Counters for coverage

- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/CoverageIdStrategy.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/ClassInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/EdgeCoverageInstrumentor.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/CoverageInstrumentationTest.kt
- driver/jvm_tooling.cpp
- driver/libfuzzer_driver.cpp
- driver/libfuzzer_driver.h
- driver/libfuzzer_fuzz_target.cpp
- examples/BUILD.bazel
When run with e.g. the -fork flag, libFuzzer delegates the fuzzing to multiple child processes running concurrently. As each of these processes runs its own JVM with its own instance of the Jazzer agent, different ranges of coverage IDs may be assigned to the same class depending on when it is discovered by that fuzzer process. Since libFuzzer collates the coverage counter buffers, this leads to misreported coverage and unnecessarily large corpora.
This PR adds a coverage ID generation strategy that uses a lockable temporary file as a means to synchronize the IDs between multiple processes.
> Sync coverage IDs between child processes

- .github/workflows/run-all-tests.yml
Incremental builds fail with supposedly undeclared dependencies on
system headers. This might be caused by changes to the underlying
GitHub virtual environment.
> Temporarily disable the Bazel cache

- agent/src/main/java/com/code_intelligence/jazzer/api/FuzzerSecurityIssueCritical.java
- agent/src/main/java/com/code_intelligence/jazzer/api/FuzzerSecurityIssueHigh.java
- agent/src/main/java/com/code_intelligence/jazzer/api/FuzzerSecurityIssueLow.java
- agent/src/main/java/com/code_intelligence/jazzer/api/FuzzerSecurityIssueMedium.java
- driver/java_reproducer_templates.h
- driver/jvm_tooling.cpp
- examples/BUILD.bazel
- examples/src/main/java/com/example/ExampleValueProfileFuzzer.java
- examples/src/main/java/com/example/JsonSanitizerCrashFuzzer.java
- examples/src/main/java/com/example/JsonSanitizerDenylistFuzzer.java
- examples/src/main/java/com/example/JsonSanitizerIdempotenceFuzzer.java
- examples/src/main/java/com/example/JsonSanitizerValidJsonFuzzer.java
Allows using `assert` in fuzz targets combined with a custom exception type for security bugs (with an optionally specified severity).
> Enable assertions and severity markup for fuzz targets

- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/TraceDataFlowInstrumentor.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/MockTraceDataFlowCallbacks.java
The switch instrumentation constructed the array of case labels incorrectly, which lead to libFuzzer performing an out-of-bounds read.
> Fix cases array construction in switch instrumentation

- BUILD.bazel
- WORKSPACE.bazel
- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/generated/BUILD.bazel
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/Instrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/runtime/NativeLibHooks.java
- agent/src/main/java/com/code_intelligence/jazzer/runtime/TraceDataFlowNativeCallbacks.java
- bazel/fuzz_target.bzl
- bazel/fuzz_target_test_wrapper.sh
- driver/BUILD.bazel
- driver/fuzz_target_runner.cpp
- driver/libfuzzer_callbacks.cpp
- driver/libfuzzer_driver.cpp
- driver/libfuzzer_fuzz_target.cpp
- driver/sanitizer_symbols_for_tests.cpp
- examples/BUILD.bazel
- third_party/BUILD.bazel
- third_party/jni/BUILD.bazel
- third_party/libFuzzer-make-interceptors-configurable.patch
- third_party/libFuzzer-pass-death-callback-to-jazzer.patch
- third_party/libFuzzer.BUILD
Reland of #45 after an accidental squash merge.
The JVM frequently calls strcmp/memcmp/..., which fills up the table of
recent compares with entries that are either duplicates of values
already reported by the bytecode instrumentation or JDK-internal strings
that are not relevant for fuzzing.
This commit adds an ignorelist to the C stdlib interceptors that filters
out calls from known JVM libraries. If the fuzz target has not yet
loaded a native library, all such callbacks are ignored, which greatly
improves fuzzer performance for string-heavy targets. E.g.,
JsonSanitizerDenylistFuzzer takes < 1 million runs now when it used to
take over 3 million.
> Do not intercept JVM-internal C stdlib calls

- agent/src/main/java/com/code_intelligence/jazzer/runtime/ExceptionUtils.kt
`takeLastWhile` preserves the order of frames and thus `reversed()` should not be applied to the result.
> Fix order of frames in StackOverflowError trace

- WORKSPACE.bazel
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/BUILD.bazel
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/EdgeCoverageInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/HookInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/HookMethodVisitor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/Instrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/TraceDataFlowInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/shade_rules
Fuzz targets may use the ASM libraries or JaCoCo themselves, which
can lead to dependency version conflicts.
To counter this, we shade all our external dependencies into the
com.code_intelligence.jazzer.third_party.* package using bazel_jar_jar
when we build the instrumentor library.
The seemingly simpler approach of applying jar shading directly to the
jazzer_agent_deploy.jar does not work as jarjar is unable to handle
some of the Kotlin runtime files in the resulting jar.
Fixes #55.
> Shade external dependencies

- examples/BUILD.bazel
Unfortunately, this is fix not as elegant as it could be (adding "manual" tag, depending on target OS).
See #65
> Disable broken tests on OSX.

- examples/BUILD.bazel
Reverts CodeIntelligenceTesting/jazzer#66
The PR breaks the IntelliJ Bazel plugin sync.
> Revert "Disable broken tests on OSX."

- agent/src/main/java/com/code_intelligence/jazzer/api/Jazzer.java
- agent/src/main/java/com/code_intelligence/jazzer/runtime/HardToCatchError.java
- agent/src/main/java/com/code_intelligence/jazzer/runtime/JazzerInternal.java
The Jazzer API call Jazzer#reportFindingFromHook would attempt to catch
the HardToCatchError (renamed from HardToCatchThrowable) wrapped in an
InvocationTargetException and exit.
With this commit, any InvocationTargetExceptions are unwrapped and the
contained HardToCatchError cause is rethrown.
> Fix InvocationTargetException in reportFindingFromHook

- agent/src/main/java/com/code_intelligence/jazzer/api/Jazzer.java
Exposes the traceStrstr and traceStrcmp callbacks through the Jazzer
API. Together with Jazzer#reportFindingFromHook, this allows for
stand-alone sanitizer libraries.
> Expose trace callbacks to API

- driver/signal_handler.cpp
Makes it possible to stop the fuzzer even if the fuzz target is in an
infinite loop. The first SIGINT lets the fuzzer exit gracefully if
possible, the second now triggers a hard exit.
> Terminate libFuzzer on second SIGINT

- .github/workflows/run-all-tests.yml
The caching action fails on macOS after hanging in the Post hook for a few minutes.
> Disable caching on macOS

- driver/libfuzzer_callbacks.cpp
- driver/sanitizer_symbols_for_tests.cpp
- repositories.bzl
This reverts commit 519d7b95b8df9abb4f872edea7313305fdab5c3c and updates
to a new version of jazzer_libfuzzer with a few reverts.
Speculative fix for crashes in memmove.
> Revert "Switch to __sanitizer_weak_hook_compare_bytes"

- driver/libfuzzer_callbacks.cpp
- driver/sanitizer_symbols_for_tests.cpp
- repositories.bzl
This reverts commit 45bd07e46afcd445879d5af0ef23dafbee1028a0.
The observed crashes were found to be unrelated to Jazzer.
> Reland "Switch to __sanitizer_weak_hook_compare_bytes"

- agent/src/main/java/com/code_intelligence/jazzer/api/Jazzer.java
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/HookMethodVisitor.kt
- agent/src/main/java/com/code_intelligence/jazzer/runtime/ManifestUtils.kt
- agent/src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java
- agent/src/main/java/com/code_intelligence/jazzer/runtime/TraceDataFlowNativeCallbacks.java
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/AfterHooks.java
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/AfterHooksTarget.java
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/AfterHooksTargetContract.java
- driver/libfuzzer_callbacks.cpp
A mix of improvements to the hooks and `Jazzer` API with the common goal to facilitate stand-alone sanitizers for e.g. SQL injections and RCE.
See the commit messages for further details.
> Improve hooks and the Jazzer API

- bazel/fuzz_target.bzl
- driver/jvm_tooling.cpp
libFuzzer defaults to an rss_limit_mb of 2048, but we start the JVM with
-Xmx4096m. This can lead to libFuzzer OOM reports when a single
allocation in Java exceeds 2 GB but still fits into the JVM heap.
This is solved by letting the JVM heap size default to slightly less
than 2 GB.
This change is not fully backwards compatible, but will only cause
targets to crash more often than they used to.
> Ensure default -Xmx value is below -rss_limit_mb

- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/generated/JavaNoThrowMethods.kt
- agent/src/main/java/com/code_intelligence/jazzer/runtime/ManifestUtils.kt
Previously these would silently remain uninstrumented as they come with
a null ClassLoader that does not pass the null check.
> Allow instrumenting internal classes

- agent/BUILD.bazel
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- format.sh
- sanitizers/BUILD.bazel
- sanitizers/sanitizers.bzl
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/BUILD.bazel
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/Deserialization.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/ReflectiveCall.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/Utils.kt
- sanitizers/src/main/java/jaz/BUILD.bazel
- sanitizers/src/main/java/jaz/Ter.java
- sanitizers/src/main/java/jaz/Zer.java
- sanitizers/src/test/java/com/example/BUILD.bazel
- sanitizers/src/test/java/com/example/ObjectInputStreamDeserialization.java
- sanitizers/src/test/java/com/example/ReflectiveCall.java
The sanitizers combine mutation guides with a dynamic proof of reachability in the form of a honeypot class that raises findings whenever it is interacted with.
The suggested severities are not fixed yet as there doesn't appear to be a broad consensus on this matter. I'm open for suggestions here. Later, we would want to extend the findings with more detailed information on the type of vulnerability.
> Implement basic remote code execution sanitizers

- bazel/cc.bzl
The driver built through the C++17 transition does not need to have the native `cc_binary` target in its runfiles, which cuts the build time almost in half and simplifies the runfiles tree.
> Prevent redundant Jazzer builds

- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
This makes using the matcher less error-prone and prevents an incorrect
log line listing all, rather than all relevant, dependencies of custom
hooks.
> Let matcher match both normal and internal class names

- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
Bail out early if we would instrument ourselves. This prevents
ClassCircularityErrors as we might need to load additional Jazzer
classes until we reach the full exclusion logic.
> Exit early for transform on internal classes

- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
Even though these classes are never instrumented by a check in `transform`, they need to be included in the default exclude list to not trigger a custom hook dependency warning.
> Readd Jazzer internal classes to exclude list

- bazel/cc.bzl
The cc_17_binary rule should not remove all runfiles from the original
target, but only the executable for the original target.
Fixes https://github.com/CodeIntelligenceTesting/jazzer/issues/116#issuecomment-846828192.
> Fix //:jazzer not finding the agent

- examples/BUILD.bazel
- examples/src/main/java/com/example/JpegImageParserFuzzer.java
- repositories.bzl
- third_party/BUILD.bazel
- third_party/libFuzzer-quote-command-args.patch
libFuzzer does not quote the arguments it passes to child processes during merge
and fork, which leads to arguments being lost if passing multiple jvm_args with
delimiter ';'.
This commit adds a libFuzzer patch that properly quotes all arguments as well as
a test that fails if quoting is not appropriate.
> Pass quoted arguments to child processes

- bazel/cc.bzl
- driver/BUILD.bazel
Applying the -std=c++17 transition on a cc_library rather than a
cc_binary has three advantages:
* saves an unnecessary transitioned build of the agent
* makes it faster to compile the driver for multiple sanitizers
* does not require a symlink in the transitioned rule
> Transition on cc_library rather than cc_binary

- driver/jvm_tooling.cpp
- examples/BUILD.bazel
- examples/src/main/java/com/example/JpegImageParserFuzzer.java
In certain situations, such as OSS-Fuzz coverage reports, additional
JVM args need to be specified on the command line after --jvm_args has
already been used. Specifying --jvm_args again overrides the previous
arguments rather than appending to them.
This commit adds an additional flag for adding JVM args that will be
emitted after the flags specified in --jvm_args.
> Add additional_jvm_args flag

- bazel/fuzz_target.bzl
- driver/BUILD.bazel
- driver/jvm_tooling.cpp
Tests automatically set `RUNFILES_DIR`, so the Bash runfiles library is not needed in the fuzz test wrapper.
> Use Bazel runfiles library to locate agent

- BUILD.bazel
- bazel/jazzer_wrapper.sh
The wrapper needs to load the Bazel Bash runfiles library to pass the
runfiles directory to jazzer_driver.
> Fix runfiles handling with jazzer_wrapper.sh

- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- driver/jvm_tooling.cpp
With `--dump_classes_dir=<dir>`, all classes that are instrumented by the
agent at runtime will be dumped into a subdirectory of `<dir>` according
to their internal class name.
> Allow dumping instrumented classes

- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/ClassInstrumentor.kt
- driver/BUILD.bazel
- driver/jvm_tooling.cpp
- driver/jvm_tooling_test.cpp
- driver/libfuzzer_driver.cpp
- driver/libfuzzer_driver.h
- driver/signal_handler.cpp
- driver/signal_handler.h
The native callbacks in the driver should be registered as early as
possible since they may already be needed during agent startup (e.g.,
if a JDK-internal class is to be instrumented).
> Register native callbacks on ClassInstrumentor initialization

- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/Hook.kt
Prepending whitespace to the target class name of a hook can now be used
to work around shading applied to hooks.
> Allow making hook target class name shade-proof

- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/runtime/ExceptionUtils.kt
This should help with issues such as
https://github.com/jhy/jsoup/issues/1577#issuecomment-877898842
> Print JVM args that reproduce OOMs & stack overflows

- driver/java_reproducer_templates.h
The Java reproducer used `getMethod` incorrectly and thus did not call
fuzzerInitialize(String[]).
> Fix reproducer template

- .bazelrc
Using the toolchain in the CI tests means that we are no longer catching
potential OSS-Fuzz build issues (see previous commit). Restrict the use
of the toolchain to the new and currently unused release config, as well
as local Maven publishing.
Also restructures some other flags in .bazelrc.
> Do not use toolchain in CI

- BUILD.bazel
- driver/BUILD.bazel
- examples/src/main/native/BUILD.bazel
Restores compatibility with gcc on linux.
> Use lld only with clang on Linux

- agent/src/main/java/com/code_intelligence/jazzer/runtime/ExceptionUtils.kt
- driver/jvm_tooling.cpp
- driver/jvm_tooling.h
- driver/libfuzzer_driver.cpp
When libFuzzer without a sanitizer times out, this prints the current stack traces of all JVM threads, e.g.:
```
==1235420== ERROR: libFuzzer: timeout after 3 seconds
Stack traces of all JVM threads:
Thread[Signal Dispatcher,9,system]
Thread[Notification Thread,9,system]
Thread[Reference Handler,10,system]
at java.base@15.0.3/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
at java.base@15.0.3/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
at java.base@15.0.3/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)
Thread[Finalizer,8,system]
at java.base@15.0.3/java.lang.Object.wait(Native Method)
at java.base@15.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
at java.base@15.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQ …
```
> Print JVM stack traces on timeouts

- agent/BUILD.bazel
- agent/agent_shade_rules
Without shading, projects using different Kotlin versions could break (or break the agent, depending on classpath order).
Related to #180
> Shade the Kotlin stdlib in the agent

- agent/src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java
The len argument to String.regionMatches may cause the regions to exceed
the length of either string, causing a StringIndexOutOfBoundsException
when taking a corresponding substring. This is fixed by capping the
compared substrings reported to the fuzzer.
> Fix regionMatches hook handling of regions exceeding the strings

- agent/agent_shade_rules
- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/BUILD.bazel
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/ClassNameGlobber.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/CoverageRecorder.kt
- repositories.bzl
- third_party/classgraph.BUILD
Using the (very fast) classpath traverser ClassPath, we can generate
coverage data for *all* classes on the classpath rather than just those
that were loaded during the fuzzing run.
> Report coverage for all classes on the classpath 

- BUILD.bazel
- WORKSPACE.bazel
- agent/src/main/java/com/code_intelligence/jazzer/api/BUILD.bazel
- repositories.bzl
Ideally, all our prod dependencies in `repositories.bzl` would link to stable release archives, which won't change even when GitHub updates their archiver. But most dependencies don't offer such archives and `git_repository` either emits warnings about missing `shallow_since` or risks breaking builds due to https://github.com/bazelbuild/bazel/issues/10292. No good solution here, so switch to releases where possible and leave the rest as is.
> Update and remove dependencies

- driver/sanitizer_hooks_with_pc.cpp
- driver/sanitizer_hooks_with_pc.h
- driver/sanitizer_hooks_with_pc_test.cpp
Since libFuzzer's integer compare hooks only feed the lowest 9 bits of
the address of the compare instruction into the value profile map, we
can reduce the size of the trampoline from 2^12 to 2^9.
> Make trampoline smaller

- driver/java_reproducer_templates.h
There is a nested catch in the crash-template which uses the 
same name "ignored" for the caught Exception as the catch on 
the outer level. 
This does not compile in Java and thus currently requires changes to crash-reproducers.
When using a unique name, this is resolved.
> Make crash-reproducers compile properly

- .bazelrc
- .github/workflows/release.yml
- .github/workflows/run-all-tests.yml
* Explicitly use macos-10.15 instead of macos-latest and reflect the
architecture in the arch key.
* Move the toolchain declaration into the CI so that local users on
macOS can use their local setup. Apple LLVM 13 may break us, but
other versions as well as mainline LLVM should work.
* Make the Ubuntu JDK 15 run an include rather than an exclude.
> Clean up CI setup

- .bazelrc
- .github/workflows/release.yml
- .github/workflows/run-all-tests.yml
- docker/jazzer/Dockerfile
Since our toolchain is loaded dynamically depending on the OS and
architecture, we can't have a static --extra_toolchains in our .bazelrc.
Instead, enable the toolchains in the specific GitHub Actions.
Fixes #260.
> Fix failure with --config=toolchain

- agent/src/main/java/com/code_intelligence/jazzer/runtime/BUILD.bazel
- agent/src/main/java/com/code_intelligence/jazzer/runtime/RecordingFuzzedDataProvider.java
- agent/src/test/java/com/code_intelligence/jazzer/runtime/BUILD.bazel
- agent/src/test/java/com/code_intelligence/jazzer/runtime/RecordingFuzzedDataProviderTest.java
Using a proxy to implement RecordingFuzzedDataProvider led to a subtle
bug related to default methods: Since the invocation handler cannot pass
the proxy instance itself to invoke (this would create a cycle), calls
to non-default methods that were internal to default methods were not
recorded as they occured on the original object.
There does not seem to be a way to fix this with proxies without either
making the FuzzedDataProvider interface aware of it being proxied (which
likely incurs a performance penalty while fuzzing) or duplicating
default method implementations.
A simple and less laborious fix is to implement the proxy object by hand
with every method delegating to the target and recording the return
value.
Fixes #265
> Fix default method recording

- agent/src/main/java/com/code_intelligence/jazzer/runtime/TraceDataFlowNativeCallbacks.java
Boxed primitives can't be directly cast to int even if their primitive
equivalent could.
> Fix ClassCastException in traceGenericCmp

- agent/src/main/java/com/code_intelligence/jazzer/runtime/JazzerInternal.java
- driver/fuzz_target_runner.cpp
This can be used to integrate agent functionality that needs to know the fuzz target class.
> Add an onFuzzTargetReady callback to the Java agent

- README.md
- bazel/fuzz_target.bzl
- driver/jvm_tooling.cpp
- examples/BUILD.bazel
- examples/src/main/java/com/example/JpegImageParserFuzzer.java
The only mechanism to specify JVM arguments currently supported by Jazzer is the `--jvm_args` argument, which has a syntax that differs between OSes and may require shell quoting.
This commit makes Jazzer honor the `JAVA_OPTS` environment variable, which is used by many popular Java tools to specify arguments to the JVMs they invoke.
Related to #279.
> Honor JAVA_OPTS

- repositories.bzl
The new version includes additional fallback logic to detect the default JVM on macOS.
> Update rules_jni to 0.4.0

- driver/fuzzed_data_provider_test.cpp
- driver/jvm_tooling_test.cpp
Some of our older tests currently set the --target_class to an internal
class name, which we don't officially support. This is causing trouble
for the Soot integration on the devassist branch, but is worth fixing on
the main branch as well.
> Use non-internal class names for target_class in tests

- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/BUILD.bazel
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/ClassInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/CoverageRecorder.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/DirectByteBufferStrategy.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/EdgeCoverageInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/runtime/CoverageMap.java
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/CoverageInstrumentationTest.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/MockCoverageMap.java
- driver/coverage_tracker.cpp
- driver/testdata/test/FuzzTargetWithCoverage.java
- third_party/jacoco-make-probe-inserter-subclassable.patch
The aim of this refactoring is to decouple the edge coverage instrumentation from the coverage map class as well as split its logic into three clearly defined parts:
* An EdgeCoverageStrategy determines the actual type of bytecode instrumentation applied, which depends on the particular nature of the counters field of the coverage map class.
* The EdgeCoverageInstrumentor class, which realizes the instrumentation strategy described by an EdgeCoverageStrategy using JaCoCo. This is the only part of the code that uses JaCoCo classes.
* The makeTestable function in the test module, which can now mock the coverage map without requiring testing-related hooks in the other parts.
This refactoring should make it easier to modify and replace parts of the edge coverage instrumenation mechanism more …
> Refactor EdgeCoverageInstrumentor

- repositories.bzl
Also update abseil-cpp to the latest release.
> Switch to .tar.gz for all dependency archives

- README.md
- docker/jazzer/Dockerfile
Now that we support three different platforms and two architectures,
maintaining an in-repo Bazelisk binary for just a single pair doesn't
make much sense anymore. Instead, provide clear and up-to-date
instructions on how to obtain and use Bazelisk to build Jazzer.
Also includes a general overhaul of the "Getting Jazzer" section of the
README and updates the Docker image to function without a checked-in
Bazelisk.
> Remove checked-in bazelisk and update README

- WORKSPACE.bazel
- repositories.bzl
(Marked as draft as it is based on #304)
GitHub support has confirmed that only the /archive/refs/tags endpoint can be assumed to return stable results over time.
For dependencies that do not offer tags we can use, I created a fork with a "commit-<SHA>" tag for the commit we were previously depending on.
Along the way, update some dependencies to their latest tag.
See this comment for more context regarding the GitHub guarantees for archive stability:
https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1029861300
> Use tags for all dependencies

- agent/src/main/java/com/code_intelligence/jazzer/agent/CoverageIdStrategy.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/utils/Utils.kt
Even though concurrent fuzzing is not fully supported situations arise in which classes are loaded concurrently (e.g. by used frameworks). This could lead to locking issues in the provided file based `SynchronizedCoverageIdStrategy`.
This PR moves the responsibility to guard access to coverage IDs from `RuntimeInstrumentor` to the concrete strategies by changing the `CoverageIdStrategy` interface. Based on their use-cases strategies can now implement different synchronization and error handling.
Now, both provided strategies synchronize coverage ID generation to support concurrent class loading.
This resolves #306
> Synchronize coverage ID generation

- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/Hook.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/InvalidHookMocks.java
REPLACE hooks on <init> can't work as only <init> can mark the stack variable as initialized.
> Disallow REPLACE hooks on <init>

- repositories.bzl
This includes fixes required to instrument java.util.regex.**.
> Update JaCoCo fork to v0.8.7-jazzer+1

- agent/src/main/java/com/code_intelligence/jazzer/autofuzz/FuzzTarget.java
- agent/src/main/java/com/code_intelligence/jazzer/autofuzz/Meta.java
- agent/src/test/java/com/code_intelligence/jazzer/autofuzz/MetaTest.java
- driver/fuzz_target_runner.cpp
- examples/BUILD.bazel
- tests/BUILD.bazel
The Autofuzz Java reproducers are based on the existing codegen
functionality and have the following advantages compared to the usual
Java reproducers generated for Autofuzz findings:
* They are completely independent of Jazzer and can thus be debugged
easily, even by developers not familiar with Jazzer.
* They are stable with respect to the classpath as they encode all
choices made during Autofuzz in literal references to classes.
* They are human-readable, especially after a straightforward pass
through IntelliJ's formatting and code cleanups.
> Standalone Autofuzz Java reproducers

- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/api/MethodHook.java
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/Hook.kt
- agent/src/main/java/com/code_intelligence/jazzer/utils/ClassNameGlobber.kt
- sanitizers/sanitizers.bzl
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/BUILD.bazel
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/OsCommandInjection.kt
- sanitizers/src/test/java/com/example/BUILD.bazel
- sanitizers/src/test/java/com/example/OsCommandInjectionProcessBuilder.java
- sanitizers/src/test/java/com/example/OsCommandInjectionRuntimeExec.java
The OS command injection sanitizer checks if fuzzer provided data reaches command execution code in `ProcessImpl::start`.
Furthermore the PR includes an extension to the `@MethodHook` annotation. The `additionalClassesToHook` property can  provide an array of classes that should be included in the hook instrumentation.
> OS command injection sanitizer

- agent/src/main/java/com/code_intelligence/jazzer/autofuzz/FuzzTarget.java
Trimming all classes in java.** and jdk.** from the stack trace made it
useless when fuzzing the Java standard library itself. Also fixes the
matching of Autofuzz classes.
> Only trim reflection and Autofuzz classes from stack trace

- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
This can happen when a hook depends on the classes to hook, e.g. because
it references the classes in a static initializer. If it turns out that
this is necessary, we would have to consider reinstrumentation.
> Warn when additionalClassesToHook are not hooked

- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/TraceDataFlowInstrumentor.kt
Now that our trampoline rightfully only forwards the lower 9 bits of the fake PC, we don't have to emit PCs larger than this in the first place.
> Do not emit unnecessarily large fake PCs

- sanitizers/src/test/java/com/example/OsCommandInjectionProcessBuilder.java
- sanitizers/src/test/java/com/example/OsCommandInjectionRuntimeExec.java
By clearing out the environment, especially PATH, it should become
extremely unlikely that the fuzzer ever executes a valid command.
Installing a SecurityManager would be even safer, but it's terminally
deprecated and incompatible with the Bazel test runner, which itself
uses a SecurityManager.
> Make OsCommandInjection tests safer

- .bazelrc
- .github/scripts/echoBuildBuddyConfig.sh
- .github/workflows/release.yml
- .github/workflows/run-all-tests.yml
Enable BuildBuddy integration when the API key is available in the
workflow. Forks should still be able to execute the workflow without
piping logs to BuildBuddy.
This is done by setting the environment variable BUILD_BUDDY_CONFIG
based on the API secret. The script echoBuildBuddyConfig returns an
environment config stating the needed bazel settings if the API token is
passed in as first argument, otherwise an empty string is returned. The
return value is used to update the workflow environment settings.
The passed around secret is filtered out in the GitHub logs.
Fixes #294
> Enable BuildBuddy integration

- README.md
- agent/BUILD.bazel
- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- tests/BUILD.bazel
- tests/src/test/java/com/example/HookDependenciesFuzzer.java
By retransforming classes that are subject to hook instrumentation after
all hooks have been loaded, we ensure that classes don't fail to be
instrumented with hooks because they are statically referenced by hooks.
This makes it easier to write efficient and readable hooks as it removes
the need for using lazy reflection to access members of classes that
should be hooked.
> Allow custom hooks to statically reference classes to hook

- .github/workflows/run-all-tests.yml
- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/api/MethodHook.java
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/BUILD.bazel
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/Hook.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/Hooks.kt
- agent/src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java
- agent/src/main/java/com/code_intelligence/jazzer/utils/ClassNameGlobber.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/AfterHooksPatchTest.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/BeforeHooksPatchTest.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/HookValidationTest.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/ReplaceHooks.java
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/ReplaceHooksPatchTest.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/ReplaceHooksTarget.java
- examples/BUILD.bazel
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/NamingContextLookup.kt
If the target type of a hook is abstract or an interface, it is applied on all its implementations.
> Support hooks on interfaces

- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/ReflectiveCall.kt
- sanitizers/src/main/java/jaz/Zer.java
- sanitizers/src/test/java/com/example/BUILD.bazel
- sanitizers/src/test/java/com/example/ClassLoaderLoadClass.java
This PR extends the hooked class loading methods and triggers a finding whenever the honeypot class is loaded and initialized.
> Extend class loading detector

- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/RegexInjection.kt
Fixes the incorrect invocation of the MethodHandle in the case where the
regex injection hook is applied to a String function, which do require
passing in the this object:
== Java Exception: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(String,String,String)String to (Object,Object)Object
 at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:881)
 at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:866)
 at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:729)
 at com.code_intelligence.jazzer.sanitizers.RegexInjection.hookInternal(RegexInjection.kt:126)
 at com.code_intelligence.jazzer.sanitizers.RegexInjection.patternHook(RegexInjection.kt:101)
...
Fixes …
> Fix regex injection hook invocation for String functions

- agent/src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java
If the argument to Map#get cannot be compared to the keys in the map due
to an incompatible type, the hook threw a ClassCastException.
To address this, we:
* Catch and ignore ClassCastException where it could be thrown.
* Reverse the compareTo calls so that the likely more lenient compareTo
function of the valid map key is used.
The original OSS-Fuzz finding that uncovered this bug:
== Java Exception: java.lang.ClassCastException: class com.alibaba.fastjson.JSONObject cannot be cast to class java.lang.Integer (com.alibaba.fastjson.JSONObject is in unnamed module of loader 'app'; java.lang.Integer is in module java.base of loader 'bootstrap')
 at java.base/java.lang.Integer.compareTo(Integer.java:64)
 at com.code_intelligence.jazzer.runtime.TraceCmpHooks.mapGet(TraceCmpHooks.java:308)
 at …
> Fix ClassCastException in mapGet hook

- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
Native library loading has a few pitfalls. This PR extracts the code out
of RuntimeInstrumentor into its own class and describes the situation in
context of the Java agent.
> Extract native library loading to dedicated class

- README.md
- WORKSPACE.bazel
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/CoverageRecorder.kt
- driver/coverage_tracker.cpp
- driver/coverage_tracker.h
- driver/fuzz_target_runner.cpp
- driver/libfuzzer_driver.cpp
- tests/BUILD.bazel
- tests/src/test/java/com/example/CoverageFuzzer.java
- third_party/jacoco_internal.BUILD
JaCoCo coverage can be used to create reports helping to identify fuzz blockers. 
The `--coverage_dump` flag can now specify a file containing coverage information that should be created after the fuzz run.
> Export JaCoCo coverage information

- agent/src/main/java/com/code_intelligence/jazzer/runtime/ExceptionUtils.kt
Timeouts can be caused by extreme GC stalls, in which case these rough
statistics can provide a first indication.
> Report simple GC stats on timeouts

- driver/fuzz_target_runner.cpp
Previously, if the fuzz target class could not be found, Jazzer would
throw an uncaught exception, which results in a c++abi terminate message
as well as a JVM native stack trace.
Now, a simple error message is shown followed by a graceful exit.
> Catch exception if fuzz target class not found

- BUILD.bazel
- agent/BUILD.bazel
- bazel/fuzz_target.bzl
- bazel/jar.bzl
- docker/jazzer/Dockerfile
- driver/BUILD.bazel
This rule is easier to use (and thus potentially upstreamable) and
correctly forwards coverage information.
> Add a Starlark rule for jar stripping

- driver/jvm_tooling.cpp
Java agent jars are automatically added to the system class loader,
which means that an explicit class path entry for them is both redundant
and potentially confusing.
> Remove redundant class path entry

- .github/workflows/check-formatting.yml
go get for binaries is no longer supported with Go 1.18.
> Use go install instead of go get in format CI job

- driver/coverage_tracker.cpp
- driver/fuzz_target_runner.cpp
Fix JNI warnings when running tests with openJ9 and `-Xcheck:jni`.
> Use CallStaticVoidMethod where applicable

- agent/src/main/java/com/code_intelligence/jazzer/api/HookType.java
- agent/src/main/java/com/code_intelligence/jazzer/api/MethodHook.java
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/HookMethodVisitor.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/ReflectiveCall.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/Utils.kt
- sanitizers/src/test/java/com/example/BUILD.bazel
- sanitizers/src/test/java/com/example/LibraryLoad.java
Since we are going to start with a blog post describing jazzer's hooking framework. We enable having multiple BEFORE and AFTER hooks for the same method. Otherwise, users might have hard to debug problems when developing bug detectors.
> Enable multiple hooks

- agent/src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java
- agent/src/test/java/com/code_intelligence/jazzer/runtime/BUILD.bazel
- agent/src/test/java/com/code_intelligence/jazzer/runtime/TraceCmpHooksTest.java
Applying `TraceCmpHooks::mapGet` to `LinkedHashMaps` can lead to `ConcurrentModificationExceptions`. 
As stated in its JavaDoc: 
> In access-ordered linked hash maps, merely querying the map with get is a structural modification.
This can easily cause concurrent modification exceptions as seen during startup of Spring Boot applications.
Strack trace of such on exception:
```
11:25:12.402 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.util.ConcurrentModificationException: null
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
at com.code_intelligence.jazzer.runtime.TraceCmpHooks.mapGet(TraceCmpHooks.java:308)
at …
```
> Prevent `ConcurrentModificationException` in `TraceCmpHooks`

- .github/workflows/release.yml
`windows-2016` runners were removed (https://github.com/actions/virtual-environments/issues/4312).
> Update windows runner in release workflow

- agent/src/main/java/com/code_intelligence/jazzer/utils/ClassNameGlobber.kt
Some Azul JDK internal classes get instrumented during startup. Add the
`com.azul.tooling` package to the exclusion list.
> Ignore Azul JDK internal classes

- driver/BUILD.bazel
We no longer use dlsym in the driver and thus don't have to link with
-ldl.
> Remove redundant -ldl linkopt

- third_party/jacoco-make-probe-inserter-subclassable.patch
Speculative fix for the following externally reported issue:
```
INFO: Instrumented com....
java.lang.StackOverflowError
at org.jacoco.core.internal.instr.ProbeInserter.visitLocalVariableAnnotation(ProbeInserter.java:126)
at org.jacoco.core.internal.instr.ProbeInserter.visitLocalVariableAnnotation(ProbeInserter.java:126)
...
...
...
at org.jacoco.core.internal.instr.ProbeInserter.visitLocalVariableAnnotation(ProbeInserter.java:126)
INFO: Instrumented com....
```
> Fix infinite recursion in ProbeInserter patch

- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/SqlInjection.kt
PreparedStatement and CallableStatement implement Statement and don't
need explicit hooks.
Fixes #420
> Remove duplicated SQL statement hooks

- examples/BUILD.bazel
- third_party/libjpeg_turbo.BUILD
The native library path for this example got lost during the migration to rules_jni and is required for the fuzz target to be functional.
> Fix TurbojpegFuzzer native library path

- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- driver/jvm_tooling.cpp
- tests/BUILD.bazel
- tests/src/test/java/com/example/DisabledHooksFuzzer.java
The new argument can be used to selectively disable both custom and and
built-in hooks.
> Add disabled_hooks CLI argument

- driver/fuzz_target_runner.cpp
- tests/BUILD.bazel
- tests/src/test/java/com/example/BytesMemoryLeakFuzzer.java
We never deleted the local reference to the byte[] array passed to the
fuzz target.
> driver: Fix memory leak for byte[] targets

- bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java
- driver/src/main/java/com/code_intelligence/jazzer/driver/Driver.java
- tests/BUILD.bazel
- tests/src/test/java/com/example/NoSeedFuzzer.java
The reduce function was misused - prev was always the first CLI
argument, not an empty Optional.
> driver: Fix driver crash when not supplying -seed 

- driver/src/main/java/com/code_intelligence/jazzer/driver/Driver.java
With -Xmx512m, the ExampleOutOfMemoryFuzzer ran into this failure on
macOS:
==19173== ERROR: libFuzzer: out-of-memory (used: 961Mb; limit: 911Mb)
> driver: Increase default -rss_limit_mb

- driver/jvm_tooling.cpp
- driver/src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetRunner.java
- driver/src/main/java/com/code_intelligence/jazzer/driver/Opt.java
Makes `--keep_going` a proper uint64 flag as it was before the Java
rewrite and ensures that the default value defined in Java is honored.
> driver: Fix --keep_going not enabled implicitly for Autofuzz

- agent/src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java
- tests/BUILD.bazel
- tests/src/test/java/com/example/JUnitAssertFuzzer.java
For now, we only hook these equals methods for object compares, but we
should add hooks for other primitive types and other common assert helpers.
> agent: Hook JUnit assertNotEquals methods

- driver/src/main/java/com/code_intelligence/jazzer/junit/JazzerFuzzTestExecutor.java
- driver/src/main/java/com/code_intelligence/jazzer/junit/RegressionTestArgumentProvider.java
- driver/src/main/java/com/code_intelligence/jazzer/junit/Utils.java
- examples/junit/src/main/java/com/example/BUILD.bazel
- examples/junit/src/main/java/com/example/Parser.java
- examples/junit/src/test/java/com/example/BUILD.bazel
- examples/junit/src/test/java/com/example/ValidFuzzTests.java
When a known coverage agent is present, also let the regression test run
over the generated corpus, if it exists.
> junit: Add support for coverage runs

- driver/src/main/java/com/code_intelligence/jazzer/driver/BUILD.bazel
- driver/src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetFinder.java
This makes it much easier to execute fuzz tests with Jazzer from build
systems such as Maven in which it is rather difficult to build a "fat"
JAR for tests.
> driver: Find @FuzzTests even if @FuzzTest is not on the classpath

- README.md
- driver/src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetRunner.java
- driver/src/main/java/com/code_intelligence/jazzer/driver/Opt.java
- examples/BUILD.bazel
- tests/BUILD.bazel
Users reported that the implicit --keep_going of Autofuzz results in
poor UX as findings fly by unnoticed and it is not clear whether fuzzing
will ever stop by itself.
Instead, stop after the first finding as usual but print helpful
follow-up commands to skip a particular finding or a finding of a
particular type.
Stacked on #472
> BREAKING: autofuzz: Do not enable --keep_going by default

- .bazelrc
- driver/src/main/java/com/code_intelligence/jazzer/junit/JazzerFuzzTestExecutor.java
- driver/src/test/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- driver/src/test/java/com/code_intelligence/jazzer/junit/DirectorySeedCorpusTest.java
- driver/src/test/java/com/code_intelligence/jazzer/junit/test_resources_root/com/example/DirectoryBasedSeedCorpus/nested_dir/seed
- examples/junit/src/test/java/com/example/DirectorySeedCorpusFuzzTest.java
- repositories.bzl
The conversion did not work on Windows, where `file:///c:/foo` became
`/C:\foo` rather than `C:\foo`.
Fixes CLI-451
> junit: Fix seed corpus URL to path conversion 

- driver/src/test/java/com/code_intelligence/jazzer/junit/AutofuzzTest.java
- examples/junit/src/test/java/com/example/AutofuzzFuzzTests.java
- examples/junit/src/test/java/com/example/ValueProfileFuzzTest.java
Before this commit:
```
//driver/src/test/java/com/code_intelligence/jazzer/junit:AutofuzzTest_fuzzing FLAKY, failed in 3 out of 10 in 301.8s
Stats over 10 runs: max = 301.8s, min = 26.4s, avg = 124.0s, dev = 118.9s
```
After this commit:
```
//driver/src/test/java/com/code_intelligence/jazzer/junit:AutofuzzTest_fuzzing PASSED in 82.4s
Stats over 20 runs: max = 82.4s, min = 14.3s, avg = 32.6s, dev = 14.5s
```
Fixes #486
> tests: Deflake tests

- bazel/tools/java/com/code_intelligence/jazzer/tools/JarStripper.java
- deploy/BUILD.bazel
- deploy/verify_shading.sh
- driver/src/main/java/com/code_intelligence/jazzer/BUILD.bazel
- driver/src/main/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- driver/src/main/java/com/code_intelligence/jazzer/junit/JazzerFuzzTestExecutor.java
- driver/src/main/java/com/code_intelligence/jazzer/junit/JazzerTestEngine.java
- driver/src/test/java/com/code_intelligence/jazzer/junit/BUILD.bazel
The automatic docs and source JAR generation provided by `rules_jvm_external`'s `java_export` couldn't handle our shading and stripping.
Fixes #474
> Generate docs and source JAR for jazzer-junit

- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/RegexInjection.kt
- sanitizers/src/test/java/com/example/BUILD.bazel
- sanitizers/src/test/java/com/example/StackOverflowRegexInjection.java
Compiling regex patterns can cause stack overflows and so the Pattern class handles this case and throws a PatternSyntaxException after unwinding the stack.
We encountered a situation where a library doesn't unwind the stack and uses a regex during handling of a stack overflow. This in turn causes another stack overflow error and the RegexInjection bug detector wrongly reports a finding.
It is very unlikely that the fuzzer triggers a stack overflow while trying to provoke a PatternSyntaxException. Hence, the RegexInjection bug detector now ignores PatternSyntaxExceptions caused by stack overflows.
Apparently stack overflow handling was introduced in JDK 14 and ported back to older versions. The exception message seems to be stable across all versions.
> Ignore regex pattern syntax exceptions caused by stack overflows

- repositories.bzl
We will use `RulesJni#extractLibrary` to extract a native library we bundle with Jazzer but preload into a separate process rather than load into the current one.
> deps: Update rules_jni to 0.6.0

- .github/workflows/release.yml
- .github/workflows/run-all-tests.yml
- `*-latest` can lead to unexpected build failures on updates
- `macos-10.15` is deprecated and started to have planned brownouts
Ref: CLI-545
> ci: Pin runner images to latest non-deprecated versions

- .bazelrc
- .github/workflows/release.yml
* Merge `jazzer` builds for all OSes as native libraries have been moved into it.
* Use rules_jvm_external's MergeJar to merge deterministically.
* Make platforms configurable via a GitHub secret so that a private fork can easily add macOS arm64 builds.
* No longer build the replayer as its functionality has been subsumed by the newly available `jazzer` Maven artifact.
> deploy: Update release workflow

- .github/workflows/check-formatting.yml
- .github/workflows/run-all-tests.yml
Gets rid of warnings about Node 12 runtime.
> ci: Update all actions

- deploy/BUILD.bazel
`jazzer-junit` uses `FuzzedDataProvider` and should thus depend on `jazzer-api` directly rather than just through `jazzer`.
> deploy: Declare a dep of `jazzer-junit` on `jazzer-api`

- WORKSPACE.bazel
- deploy/jazzer-junit_artifact_test.sh
Before https://github.com/bazelbuild/rules_jvm_external/commit/90280783fa4e74439b88191acafd99232ada61aa, parent directories of files were not necessarily included in JARs generated with `java_export`, which could confuse Java tooling expecting them to exist.
> deps: Update rules_jvm_external to preserve directories in JARs

- agent/src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/BUILD.bazel
- driver/src/main/java/com/code_intelligence/jazzer/BUILD.bazel
- driver/src/main/java/com/code_intelligence/jazzer/junit/AgentConfigurator.java
- driver/src/main/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/BUILD.bazel
I forgot to add the deploy manifest line to `jazzer_standalone_deploy.jar`. Since this is error-prone, use code generation to load the list of built-in hooks instead in a single location.
Also add a check to verify that built-in hooks are loaded. This would have let existing tests catch this regression.
> Fix sanitizers not being loaded with jazzer_standalone_deploy.jar

- driver/src/main/java/com/code_intelligence/jazzer/BUILD.bazel
> driver: Make `jazzer_standalone.jar` executable without the launcher

- CONTRIBUTING.md
- deploy/BUILD.bazel
- driver/src/main/java/com/code_intelligence/jazzer/BUILD.bazel
Getting clickable cross-references in Javadocs requires publishing the docs in order, which is documented in the new `CONTRIBUTING.md` guide.
> deploy: Host linked javadocs for all Maven artifacts

- README.md
- docker/jazzer-autofuzz/Dockerfile
- docker/jazzer/Dockerfile
Also updates Bazelisk and removes `python-is-python3`, which is no longer needed with Bazel 6.
Fixes #558
> docker: Update to OpenJDK 17

- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestArgumentsProvider.java
JUnit identifies individual runs of a `@ParameterizedTest` via their invocation number. In order to get reproducible behavior e.g. when trying to debug a particular input, all inputs thus have to be provided in deterministic order.
This is achieved by sorting all inputs by path in their respective groups: The empty input always comes first, then the inputs directory contents in path order, then (only with coverage) the generated corpus in path order.
> junit: Sort inputs by path

- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/ExpressionLanguageInjection.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/OsCommandInjection.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/ReflectiveCall.kt
For all hooks where we don't specify a method descriptor, we now check the size of the parameters before accessing them.
> Check arguments size in all hooks without a method descriptor

- examples/junit/src/test/java/com/example/HermeticInstrumentationFuzzTest.java
- src/jmh/java/com/code_intelligence/jazzer/instrumentor/CoverageInstrumentationBenchmark.java
- src/jmh/java/com/code_intelligence/jazzer/instrumentor/EdgeCoverageInstrumentation.java
- src/main/java/com/code_intelligence/jazzer/agent/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/driver/Opt.java
- src/main/java/com/code_intelligence/jazzer/instrumentor/ClassInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/EdgeCoverageInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/HookInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/HookMethodVisitor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/Instrumentor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/TraceDataFlowInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/junit/AgentConfigurator.java
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTest.java
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExtensions.java
- src/main/java/com/code_intelligence/jazzer/runtime/JazzerInternal.java
- src/test/java/com/code_intelligence/jazzer/instrumentor/AfterHooksPatchTest.kt
- src/test/java/com/code_intelligence/jazzer/instrumentor/BeforeHooksPatchTest.kt
- src/test/java/com/code_intelligence/jazzer/instrumentor/CoverageInstrumentationTest.kt
- src/test/java/com/code_intelligence/jazzer/instrumentor/ReplaceHooksPatchTest.kt
- src/test/java/com/code_intelligence/jazzer/instrumentor/TraceDataFlowInstrumentationTest.kt
- src/test/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/junit/HermeticInstrumentationTest.java
- src/test/java/com/code_intelligence/jazzer/junit/RegressionTestTest.java
This makes it possible to run fuzz tests alongside unit tests without having the instrumentation applied by the agent interfere with unit tests, e.g. by throwing unexpected exceptions.
> junit: Disable hooks in non-fuzz tests during regression testing 

- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExecutor.java
On Windows, `Paths.get("")` does not behave like the current working directory when used to resolve other paths relative to it. Instead, convert it to an absolute path.
Fixes #546
> junit: Fix working directory path construction on Windows

- .github/workflows/release.yml
We pin the Xcode version in our build & test workflow as detecting host Xcodes is slow and frequently led to timeouts on the slow macOS runners. Since our release workflow uses an older version of macOS, it may not have the pinned Xcode available.
> ci: Do not pin Xcode version in release workflow

- src/main/java/com/code_intelligence/jazzer/autofuzz/Meta.java
- src/test/java/com/code_intelligence/jazzer/autofuzz/MetaTest.java
Before this commit, `consume` would construct an `Object[]` when a `Class<?>[]` was requested, leading to `IllegalArgumentExeption`s.
Fixes #582
> autofuzz: Fix handling of generic array types 

- src/main/java/com/code_intelligence/jazzer/autofuzz/Meta.java
- tests/BUILD.bazel
- tests/src/test/java/com/example/AutofuzzCrashingSetterTarget.java
When an invocatin of `autofuzz` in `consume` fails, this is not a finding but rather a failure to construct a valid object.
> autofuzz: Do not report finding for failed autofuzz in consume

- .bazelrc
Due to a Bazel issue (https://github.com/bazelbuild/bazel/pull/17158), the recent introduction of `universal_binary` ended up forking the configuration for dependencies of the Jazzer launcher. As a result, some Java targets were built twice and the Docker images failed to build as the Jazzer standalone jar was no longer a dependency of the launcher in the default configuration.
As a workaround and also because it prevents similar issues on a more fundamental level, switch to the soon to be default improved config hash algorithm.
> Fix Docker build and prevent unnecessary rebuilds

- examples/BUILD.bazel
- examples/src/main/java/com/example/ExampleKotlinValueProfileFuzzer.kt
- src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java
Kotlin's integral types have `compareTo` methods that are compiled to calls into one of two `compare` overloads from the `kotlin.jvm.internal.Intrinsics` class:
1. `public static int compare(long thisVal, long anotherVal)`
2. `public static int compare(int thisVal, int anotherVal)`
> agent: Hook Kotlin's compare method for integral types

- src/main/java/com/code_intelligence/jazzer/utils/Log.java
When a message is logged without a stack trace, it should not end with a colon.
> all: Do not end all log messages with a colon

- examples/junit/src/test/java/com/example/DirectoryInputsFuzzTest.java
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExecutor.java
- src/main/java/com/code_intelligence/jazzer/junit/Utils.java
- src/test/java/com/code_intelligence/jazzer/junit/AutofuzzTest.java
- src/test/java/com/code_intelligence/jazzer/junit/FuzzingWithoutCrashTest.java
Inputs directory handling was confusing as e.g. Maven doesn't copy over empty resource directories by default. Instead of relying on that, always fall back to locating the inputs directory in the source tree and even try to create it if at least the test resources root is found.
> junit: Simplify and improve inputs directory discovery

- examples/junit/src/test/java/com/example/LifecycleFuzzTest.java
- src/main/java/com/code_intelligence/jazzer/driver/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetFinder.java
- src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetInstanceHolder.java
- src/main/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExecutor.java
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExtensions.java
This ensures compatibility with non-trivial test class constructors and test instance post processing, which is common with mocking frameworks such as Mockito.
> junit: Use JUnit-provided test instance

- docs/advanced.md
- src/main/java/com/code_intelligence/jazzer/Jazzer.java
In OSS-Fuzz, `clang` is only available at build time, not when the fuzzer is executed. It thus can't be used to find the native sanitizer libraries.
Instead, make it possible to specify the directory containing the shared libraries with the new `JAZZER_NATIVE_SANITIZERS_DIR` env variable.
> driver: Make native sanitizer lib location overridable 

- examples/BUILD.bazel
- src/jmh/java/com/code_intelligence/jazzer/runtime/BUILD.bazel
These tests reproducibly fail on Windows due to high memory usage.
> ci: Run memory-hungry tests in isolation

- repositories.bzl
The new version is ~10% faster and supports versioned class files, which gets rid of a number of build warnings.
> bazel: Update bazel_jar_jar

- src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/TraceDataFlowInstrumentor.kt
- src/test/java/com/code_intelligence/jazzer/instrumentor/CoverageInstrumentationTest.kt
Some `@OptIn`s aren't needed anymore, the other can be replaced with dedicated annotations that do not require special compiler flags.
> agent: Fix Kotlin compiler warnings about `@OptIn`

- repositories.bzl
- tests/BUILD.bazel
- tests/src/test/java/com/example/OfflineInstrumentedFuzzer.java
- tests/src/test/java/com/example/OfflineInstrumentedTarget.java
- third_party/jacoco-ignore-offline-instrumentation.patch
JaCoCo is able to offline instrument classes. It determines if classes,
which should be instrumented dynamically, are already instrumented by
checking the existence of the coverage data field, and throws an
exception if it's present.
Jazzer's `IProbeArrayStrategy` already does not add the coverage data
field. This PR also removes JaCoCo's check if the field is present, and
so enables fuzzing of offline instrumented classes.
> Ignore offline instrumentation

- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/ListMutatorFactory.java
The list view is backed by an `ArrayList`, so random access is efficient and we should forward that information to the user.
> mutation: Let ImmutableListView implement RandomAccess 

- src/main/java/com/code_intelligence/jazzer/mutation/combinator/MutatorCombinators.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorFactory.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorProto3Test.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/proto3.proto
While `oneof`s were handled by the existing code, the mutator wasn't aware of the `oneof`'s state and would thus change it frequently, which ends up invalidating mutations applied to its other fields.
With this commit, `oneof` fields have their current state tracked and mutated in 1 out of 100 cases, which allows individual fields to reach more complicated states.
> mutation: Add explicit support for oneof message fields

- .bazelrc
By setting `--test_env` also for the `build` command, where it is ignored, Bazel doesn't have to reanalyse the project between `build` and `test` invocations.
> bazel: Avoid analysis cache clearing

- examples/junit-spring-web/build-and-run-tests.sh
- examples/junit/src/test/java/com/example/BUILD.bazel
- examples/junit/src/test/java/com/example/KeepGoingFuzzTest.java
- src/main/java/com/code_intelligence/jazzer/driver/Driver.java
- src/main/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExecutor.java
- src/main/java/com/code_intelligence/jazzer/junit/Utils.java
- src/test/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/junit/UtilsTest.java
The transitive dependency on `org.junit.platform:junit-platform-launcher` removes the need to specify it manually in every project.
> junit: Add transitive dependency on launcher

- src/main/java/com/code_intelligence/jazzer/autofuzz/Meta.java
Classes without a canonical name cannot be instantiated by reproducers and thus also shouldn't be used by Autofuzz. If we find constructing them useful, we should instead look for factory methods.
Fixes #619
> autofuzz: Filter out unnamed classes

- .bazelrc
- .github/workflows/release.yml
- CONTRIBUTING.md
- deploy/deploy.sh
This simplifies the setup for contributors as well as the release process. Since we can't use `--release 8`, we still need to check compatibility with Java 8 runtime libraries in our CI, which still uses the local JDK 8 to run tests against.
Also removes stamping from Maven builds as we already have the version number baked in.
> bazel: Use a hermetic Java toolchain compiling for Java 8

- BUILD.bazel
- launcher/fuzzed_data_provider_test.cpp
- launcher/jazzer_main.cpp
- launcher/jvm_tooling.cpp
- launcher/jvm_tooling.h
- launcher/jvm_tooling_test.cpp
- src/main/java/com/code_intelligence/jazzer/Jazzer.java
- tests/BUILD.bazel
- tests/src/test/shell/jazzer_from_path_test.sh
When Jazzer is executed from `PATH`, `argv[0]` will just be `jazzer`, which we can't find `jazzer_standalone.jar` relative to.
Also fix `argv[0]` in the case where no shell launcher is generated.
Fixes #641
> launcher: Use actual executable path instead of `argv[0]`

- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorFactory.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/proto2.proto
The index obtained from the field descriptor was the index in the whole message, not necessarily the index in the oneof.
> mutator: Fix computation of oneof subfield index

- sanitizers/src/test/java/com/example/ObjectInputStreamDeserialization.java
- src/main/java/jaz/Zer.java
readObject calls can directly result in RCE, see https://github.com/frohoff/ysoserial for examples. Since deserialization doesn't call constructors (see https://docs.oracle.com/javase/7/docs/platform/serialization/spec/input.html#2971), we emit a finding right in the readObject method.
> sanitizers: Reenable RCE reports for `readObject` calls

- src/main/java/com/code_intelligence/jazzer/mutation/mutator/lang/ByteArrayMutatorFactory.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/BUILD.bazel
- tests/BUILD.bazel
- tests/src/test/java/com/example/ExperimentalMutatorComplexProtoFuzzer.java
Without this change, the simple new fuzz test fails to find the planted bug. With this change, it finds it in less than 20,000 runs.
> mutator: Use shorter initial sizes for byte arrays

- src/main/java/com/code_intelligence/jazzer/mutation/annotation/proto/AnySource.java
- src/main/java/com/code_intelligence/jazzer/mutation/annotation/proto/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorFactory.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/TypeLibrary.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorProto3Test.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/proto3.proto
The annotation controls the message types used for Any proto fields in (recursive) submessages.
This requires passing the annotation through to message field types as well as extending the mutator cache key to cover the annotation value.
> mutator: Add AnySource annotation

- docker/jazzer/Dockerfile
`gcr.io/distroless/java:debug` still refers to Java 11, so switch to `gcr.io/distroless/java17:debug` for Java 17 support.
> docker: Support Java 17 in Jazzer docker image

- src/main/java/com/code_intelligence/jazzer/api/AutofuzzInvocationException.java
- src/main/java/com/code_intelligence/jazzer/autofuzz/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/autofuzz/Meta.java
- src/main/java/com/code_intelligence/jazzer/runtime/BUILD.bazel
Autofuzz tries to print caught exceptions, but this fails in case of bug detector findings, as the thrown exceptions are intentionally hard to catch and rethrow themselves if possible.  Due to this behavior the following line is potentially loged multiple times: `ERROR: Unexpected exception encountered during autofuzz:`
In this case the exceptions are also only used to abort the current invocation, logging of the actual findings is done by different means. So it's save to ignore this kind of exceptions.
Fixes #696
> autofuzz: Fix logs for bug detector findings

- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/MapMutatorFactory.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/MapMutatorTest.java
This changes the map size handling similar to what was done in #675 to prevent the oscillation around `maxSize` by doing a fair random pick of the mutation operator
> map mutator improvements

- .bazelrc
- .github/workflows/check-formatting.yml
- BUILD.bazel
- CONTRIBUTING.md
- WORKSPACE.bazel
- bazel/kotlin.bzl
- bazel/toolchains/BUILD.bazel
- bazel/toolchains/editorconfig.ktlint
- examples/BUILD.bazel
- format.sh
- launcher/android/AndroidManifest.xml
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/BUILD.bazel
- src/jmh/java/com/code_intelligence/jazzer/instrumentor/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/agent/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/driver/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/instrumentor/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/utils/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/instrumentor/BUILD.bazel
- tests/BUILD.bazel
- third_party/jacoco_internal.BUILD
- third_party/libFuzzer.BUILD
This speeds up the format script and reduces the number of tools developers need to have installed locally.
> bazel: Run all formatters with Bazel

- launcher/fuzzed_data_provider_test.cpp
We aren't going to make any changes to the UTF-8 fixup routine in `FuzzedDataProvider` and the test is fully deterministic, so we can reduce the number of runs to prevent frequent timeouts on macOS.
> tests: Speed up fuzzed_data_provider_test

- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderAdapters.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderAdaptersTest.java
Ensures that individual bulk operations never require more than linear time.
Also improves the test by asserting that the underlying builder is modified rather than just the view.
> mutation: Improve list adapter for repeatable fields

- src/main/java/com/code_intelligence/jazzer/mutation/api/PseudoRandom.java
- src/main/java/com/code_intelligence/jazzer/mutation/engine/SeededPseudoRandom.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/ChunkMutations.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/ListMutatorFactory.java
- src/test/java/com/code_intelligence/jazzer/mutation/ArgumentsMutatorTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/engine/SeededPseudoRandomTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/ChunkMutationsTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/ListMutatorTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorProto2Test.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorProto3Test.java
- src/test/java/com/code_intelligence/jazzer/mutation/support/TestSupport.java
Adds chunk-based mutations to the list mutator mimicking fuzztest's mutation.
The size of the chunks is chosen according to a Zipf distribution, which ensures that chunks tend to be small (and often have length 1), which should result in more stable mutations and also makes separate individual element mutations unnecessary.
> mutation: Improve ListMutator

- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
The rare case happens for proto float/double fields that are initiated with -0.0/-0.0f; detached to 0.0/0.0f; and mutated back to -0.0/-0.0f. This previously caused a rare random failure of the StressTest.java.
> mutator: fix a rare test case

- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/ChunkMutations.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/ListMutatorFactory.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/MapMutatorFactory.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/libfuzzer/LibFuzzerMutator.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/ChunkMutationsTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/ListMutatorTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/MapMutatorTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/support/TestSupport.java
The previous Map mutator performed both single element as well as chunk
mutations, which isn't necessary now that we can bias chunks towards
being small.
The old implementation didn't check that `initInPlace` and `read` obeyed
the specified `minSize`. Since non-zero `minSize`s can be problematic in
`read`, they are not supported for now.
There were also a few issues with key mutations: Instead of retrying key
creation separately for each key, which can result in a large amount of
wasted attempts if the key set is almost saturated, all such attempts
now share a single failure counter. Keys are now properly detached
before being mutated, which is necessary if map keys are mutable.
The fallback to value mutation if key mutation failed also didn't
behave correctly: It called `setValue` on a …
> mutation: Use chunk-based mutation approach for Map 

- .github/workflows/run-all-tests.yml
Should help us debug the failures in https://github.com/CodeIntelligenceTesting/jazzer/pull/711.
> ci: Make Bazel log available as artifact

- WORKSPACE.bazel
Includes bazel-contrib/rules_jvm#175, which adds causes to JUnit stack traces.
> bazel: Update rules_jvm

- .github/workflows/run-all-tests.yml
On Windows, `bazel test` uses a different `PATH` value than `bazel build`, which results in duplicated build steps. Since `bazel test //...` also builds all targets, the additional `build` step does not provide additional assurances.
This may also resolve `failed to delete output files` errors which occur during the test step, likely because the build step leaks open files somewhere.
> ci: Merge `bazel build` and `bazel test`

- .bazelrc
- launcher/jvm_tooling.cpp
See changes in the following files:
- https://github.com/CodeIntelligenceTesting/jazzer/commit/0e9555aecbb39dfdd354728b46c7cec4b5a900bc
- https://github.com/CodeIntelligenceTesting/jazzer/commit/07bd293d2f686a7b8131d2617602a8e5b7640ebc
These broke our build commands:
- bazelisk build launcher/android:jazzer_android --config=android_arm
- bazelisk build src/main/java/com/code_intelligence/jazzer/android:jazzer_standalone_android --config=android_arm
> Fix breakages to android builds due to toolchain issues

- src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- tests/src/test/java/com/example/CoverageFuzzer.java
Reason:
JaCoCo produces wrong coverage because the coverage instrumentation happens after the hooks are set.
This instrumentation should follow the JaCoCo algorithm but in fact they produce different results.
Both algorithms inject control points into the end of each BB where the INVOKE happens.
BBs where there are no INVOKEs are not marked.
Let's check the case: BBs originally did not have any INVOKE but hooks are injected traceCmp callback.
CoverageRecorder happily adds a control point into such a BB but JaCoCo will never know about this.
As the result, all points after the mentioned will be misplaced in JaCoCo coverage.
Sample for test:
package com.example;
import java.util.Random;
public class Junit5Example1 {
public static boolean earlyReturn = false;
public static boolean …
> Patch: update instrumentation order to fix coverage

- src/main/java/com/code_intelligence/jazzer/mutation/combinator/MutatorCombinators.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/proto3.proto
Otherwise, it could cause a check failure.
> Avoids changing the mutator when there's only one.

- .bazelrc
- launcher/jvm_tooling.cpp
Using default "local_jdk" for java_runtime_version.
initializing var read_bytes. It will not be used, but for compilation needs to be defined.
> Fixed Android build breaks

- src/main/java/com/code_intelligence/jazzer/mutation/combinator/MutatorCombinators.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorFactory.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/TypeLibrary.java
- src/main/java/com/code_intelligence/jazzer/mutation/support/TypeSupport.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorProto2Test.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorProto3Test.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/proto2.proto
- src/test/java/com/code_intelligence/jazzer/mutation/support/TypeSupportTest.java
When recursive proto fields are initialized, the resulting messages have an expected nesting depth on the order of the inverse of the frequency with which a nullable value is non-null, which tends to run into StackOverflowErrors quickly.
This is fixed by checking whether a given proto field is recursive and if so, only initializing it "layer by layer" in mutations rather than all at once during initialization.
> mutation: Do not initialize recursive proto fields

- .bazelrc
- CONTRIBUTING.md
- bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java
Jazzer integration tests can be debugged by passing `--config=debug` and attaching to the suspended JVM.
> bazel: Add debug config

- src/main/java/com/code_intelligence/jazzer/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestArgumentsProvider.java
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExtensions.java
- src/main/java/com/code_intelligence/jazzer/junit/Utils.java
- src/main/java/com/code_intelligence/jazzer/junit/junit_shade_rules
- src/main/java/com/code_intelligence/jazzer/utils/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/utils/UnsafeUtils.java
- src/test/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/junit/UtilsTest.java
This is intended to be a pure refactoring that enables us to allow arbitrary `ArgumentsProvider`s to provide arguments for fuzz tests that are picked up in fuzzing mode.
> junit: Use marker arguments to signal start of fuzzing

- src/main/java/com/code_intelligence/jazzer/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/Jazzer.java
- src/main/java/com/code_intelligence/jazzer/agent/AgentInstaller.java
- src/main/java/com/code_intelligence/jazzer/agent/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/driver/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/driver/Driver.java
- src/main/java/com/code_intelligence/jazzer/driver/ExceptionUtils.kt
- src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetFinder.java
- src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetRunner.java
- src/main/java/com/code_intelligence/jazzer/driver/Opt.java
- src/main/java/com/code_intelligence/jazzer/driver/SignalHandler.java
- src/main/java/com/code_intelligence/jazzer/runtime/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/runtime/Constants.java
- src/main/java/com/code_intelligence/jazzer/runtime/FuzzTargetRunnerNatives.java
- src/main/java/com/code_intelligence/jazzer/runtime/NativeLibHooks.java
We can detect whether we are running on Android via system properties and thus don't need to have this bit passed in via a flag.
As a result, the runtime no longer depends on Opt, which is thus no longer loaded in the bootstrap class loader in addition to the system class loader.
> all: Only load Opt in the system class loader

- src/main/java/com/code_intelligence/jazzer/Jazzer.java
`-fork=0` and similar flags disable the respective libFuzzer modes and thus should not lead Jazzer to prepare for being run in a subprocess, e.g., not set `-seed`.
Fixes #756
> driver: Do not prepare for a subprocess for `-fork=0`

- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorFactory.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/MessageMutatorTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/proto/proto2.proto
A proto message deserialized from bytes can be incomplete, which results in an error when building it if required fields are missing. To prevent this, walk the proto and initialize all unset required fields to defaults recursively.
> mutator: Set required fields to defaults when reading incomplete proto

- src/main/java/com/code_intelligence/jazzer/mutation/annotation/proto/WithDefaultInstance.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/BuilderMutatorFactory.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/proto/TypeLibrary.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
- tests/src/test/java/com/example/ExperimentalMutatorDynamicProtoFuzzer.java
A default instance is a more direct representation of a protobuf base message and getting it via a method allows for more flexible use, e.g., by making the choice of proto type dependent on command-line arguments.
> Replace `@DescriptorSource` with `@WithDefaultInstance`

- src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/junit/AgentConfigurator.java
- src/main/java/com/code_intelligence/jazzer/utils/ClassNameGlobber.kt
Some JetBrains products interact badly with Jazzer's agent / instrumentation, e.g. their coverage agent. It's reasonable to ignore all JetBrains classes.
> Ignore JetBrains classes during instrumentation

- src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java
I could have reused `assertEquals` [[L]](https://github.com/CodeIntelligenceTesting/jazzer/blob/3869b7395de165e94093379e83adf6e978871cb7/src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java#L584). But since this is not an assertion-hook, I decided to write a new function in proximity to `genericEquals` [[L]](https://github.com/CodeIntelligenceTesting/jazzer/blob/3869b7395de165e94093379e83adf6e978871cb7/src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java#L94).
~Also I'm not totally sure, what the meaning of the `Boolean areEqual` parameter is? (In `assertEquals` it is called `Object alwaysNull` and in the [ExampleHook](https://github.com/CodeIntelligenceTesting/jazzer/blob/main/examples/src/main/java/com/example/ExampleFuzzerHooks.java) it's not defined …
> hooks: Add equals-hook for Clojure (clojure.lang.Util.equiv)

- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExecutor.java
This removes a potential source of non-deterministic behavior while fuzzing with a fixed `-seed`.
> junit: Generate temporary seeds with deterministic names

- src/main/java/jaz/Zer.java
This change allows Zer to compile with JDK 21, which adds new methods to the collections API for https://openjdk.org/jeps/431
Fixes https://github.com/CodeIntelligenceTesting/jazzer/issues/781
> Add an override of reversed to Zer for compatibility with JDK 21

- README.md
This adds a short note to the readme to point out that we have instructions on building Jazzer from source in contributing.md
Closes #760
> Add a line in the readme to point out instructions for building

- docker/jazzer/Dockerfile
> make '/usr/bin/env' available in docker container

- src/main/java/com/code_intelligence/jazzer/driver/ReproducerTemplate.java
The message erroneously contained the help string for the `--reproducer_path` instead of the value.
> driver: Fix reproducer_path log message

- src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java
- tests/BUILD.bazel
- tests/src/test/java/com/example/PrimitiveTypeCompareHookFuzzer.java
Previously, calls to `{Byte,Short}.compare{Unsigned,}` resulted in exceptions such as the following:
```
java.lang.ClassCastException: class java.lang.Short cannot be cast to class java.lang.Integer (java.lang.Short and java.lang.Integer are in module java.base of loader 'bootstrap')
at com.code_intelligence.jazzer.runtime.TraceCmpHooks.integerCompare(TraceCmpHooks.java:40)
...
```
Fixes #790
> runtime: Fix ClassCastException for primitive `compare` calls

- .github/workflows/fuzzing.yaml
PRs from forks will fail because they won't have the required API key for CI Sense so this changes our fuzz test workflow to skip them if the key is not there.
Should unstuck #780
> Change fuzzing to only execute if the secret is available

- .bazelrc
This is a new feature that will be enabled by default soon, but should already be stable enough to speed up our builds with.
This requires updating Bazel to fix https://github.com/bazelbuild/bazel/issues/18969.
> bazel: Start building before all external deps are fetched 

- .bazelrc
- .github/workflows/run-all-tests.yml
- bazel/compat.bzl
- launcher/android/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/Jazzer.java
- src/main/java/com/code_intelligence/jazzer/android/AndroidRuntime.java
- src/main/java/com/code_intelligence/jazzer/android/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/driver/OfflineInstrumentor.java
- src/main/java/com/code_intelligence/jazzer/utils/ZipUtils.java
- src/main/native/com/code_intelligence/jazzer/android/BUILD.bazel
- src/main/native/com/code_intelligence/jazzer/driver/BUILD.bazel
- src/main/native/com/code_intelligence/jazzer/driver/android_tooling.cpp
This is to correct the Android build targets compatibility configuration. This makes the Android build targets only compatible when building for Android target.
This will also add a check that will fail with a message when building for Android on a non-linux host machine. This is because:
1. Android modules aren't supported on Windows
2. the genrule command needed for jvmti.h doesn't work on Mac
> Add new ANDROID_ONLY compatibility option

- .gitattributes
- bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java
- selffuzz/cifuzz.yaml
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExecutor.java
- tests/BUILD.bazel
- tests/src/test/java/com/example/JUnitReproducerTest.java
- tests/src/test/java/com/example/JUnitReproducerTest.seed
When all user-provided libFuzzer path arguments are files, the JUnit
executor now correctly starts libFuzzer in reproduction mode by not
adding any directories to the command line. In particular, this fixes
a crash when Jazzer is invoked on a single file to reproduce a
particular finding.
> junit: Fix CLI runs on individual files 

- src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetFinder.java
This adds a new note to the error message that appears when the `@FuzzTest` is used, but JUnit 5 is not set up / the dependency `junit-jupiter-engine` in missing in version 5.
> driver: Enhance method-not-found errors when not using JUnit 5

- maven.bzl
0.20.0 is broken on Maven as reported in https://github.com/CodeIntelligenceTesting/jazzer/issues/836.
> deploy: Bump version to 0.20.1

- src/main/java/com/code_intelligence/jazzer/instrumentor/HookMethodVisitor.kt
Use the structured logging class instead.
> instrumentor: Do not emit Java 7 warning to stdout

- selffuzz/cifuzz.yaml
This changes the timeout for fuzzing in CI Sense to 5 minutes. Since the same corpora are used for subsequent fuzzing runs, it is not necessary to run for 30 minutes for every branch pushed.
> Change cifuzz timeout value to 5 minutes

- repositories.bzl
- src/main/java/com/code_intelligence/jazzer/junit/BUILD.bazel
- third_party/rules_jvm_external-add-neverlink-deps-to-javadoc-classpath.patch
The user has to add and control this dependency themselves if they want
to use JUnit 5. Even if we added it, Maven resolution mechanics mean
that we do not control the version anyway.
This fixes an issue introduced by 1ca007d04325014d4fa0e48d239745f3ecc8fbcf.
See https://github.com/junit-team/junit5/discussions/3441#discussioncomment-6884855
Also require fixing an issue in rules_jvm_external that results in
neverlink deps not appearing on the javadoc classpath.
> junit: Do not depend on `junit-jupiter-engine`

- src/main/java/com/code_intelligence/jazzer/junit/FuzzTest.java
- tests/src/test/java/com/example/JUnitTimeoutTest.java
This can be used to create custom reusable variants of `@FuzzTest`. `cifuzz` added support for this in https://github.com/CodeIntelligenceTesting/cifuzz/pull/986.
> Allow `@FuzzTest` to be applied to annotations

- .github/workflows/prerelease.yaml
- .github/workflows/release.yml
- CONTRIBUTING.md
- deploy/deploy.sh
This PR automates the release process by creating
- Github releases
- git tags
- Maven artifacts
- Docker images
- documentation
in the CI pipeline.
More Information in first commit message.
> Release in CI pipeline

- src/main/java/com/code_intelligence/jazzer/junit/FuzzTestExecutor.java
- src/test/java/com/code_intelligence/jazzer/junit/CorpusDirectoryTest.java
If users add custom corpus directories, the first of those will be used as the generated corpus instead of the default `.cifuzz-corpus` directory. We now no longer create this directory if it is going to stay empty because it isn't used as the generated corpus directory.
> junit: Only create `.cifuzz-corpus` if it is the generated corpus

- deploy/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/BUILD.bazel
> deploy: Fix `jazzer_standalone.jar` not being executable

- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
StressTest required a lot of memory since it collected all `init` and `mutate` return values in a list. Instead, cross values off a short list for "contains" type checks and use `hashCode()` to stand in for the actual value in statistical tests.
Verified locally that the test now passes with `--jvmopt=-Xmx512M`.
> tests: Do not retain values in StressTest

- src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/Hooks.kt
At least for JDK/JRE 8, these directories contain `.jar` files with classes that may need to be instrumented.
Fixes #866
> Also scan `lib/` and `ext/` `.jar`s with ClassGraph

- bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java
This broke in 55eb18b20953bea99fa1a5f55668740686f448b3.
> tests: Restore live output of `java_fuzz_target_test`

- src/main/native/com/code_intelligence/jazzer/driver/libfuzzer_callbacks.cpp
Fixes a JVM crash with the following frame while fuzzing native libraries:
```
[libstdc++.so.6+0x13bf8a]  std::ostream::sentry::sentry(std::ostream&)+0x1a
```
> driver: Fix startup crash when fuzzing native libraries

- README.md
... before archiving this repository
> docs: update readme to inform about commercial offering

- .github/workflows/prerelease.yaml
This workflow failed before because 
> Error
> softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981 is not allowed to be used in CodeIntelligenceTesting/jazzer. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or matching the following: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d.
> ci: Update softprops/action-gh-release to v2.2.0 in prerelease workflow

- .github/workflows/prerelease.yaml
- .github/workflows/release.yml
Downgrade softprops/action-gh-release again to v2.0.9 because of https://github.com/softprops/action-gh-release/issues/556
Sets the release pipeline to run automatically when the github draft release is released
> Fix prerelease pipeline

- deploy/BUILD.bazel
- deploy/jazzer-api.pom
- deploy/jazzer-junit.pom
- deploy/jazzer.pom
Adds license and developer information to maven pom files.
Adds necessary source and javadoc jars for `jazzer-api` and `jazzer-junit` required for maven publishing
> Fix maven deployment

- deploy/BUILD.bazel
- deploy/jazzer-api_artifact_test.sh
- src/main/java/com/code_intelligence/jazzer/api/Autofuzz.java
- src/main/java/com/code_intelligence/jazzer/api/MethodHook.java
- src/main/java/com/code_intelligence/jazzer/mutation/annotation/UrlSegment.java
- src/main/java/com/code_intelligence/jazzer/mutation/utils/ValidateContainerDimensions.java
- src/main/java/com/code_intelligence/jazzer/mutation/utils/ValidateMinMax.java
See individual commit messages. This still requires https://github.com/bazel-contrib/rules_jvm_external/pull/1308, which can be brought in via an `archive_override` after it has been merged or as a patch before that.
Work towards #919
> Fix Maven releases

- sanitizers/sanitizers.bzl
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/BUILD.bazel
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/FilePathTraversal.java
- sanitizers/src/test/java/com/example/AbsoluteFilePathTraversal.java
- sanitizers/src/test/java/com/example/BUILD.bazel
- sanitizers/src/test/java/com/example/FilePathTraversal.java
This adds a FilePathTraversal sanitizer. 
Harnesses set directories under which the application may read and write files via an environment variable.
This does not currently handle symlinks.
> Add a path traversal sanitizer

- README.md
Follow-up for #942
The `run-all-tests-main.yml` workflow does not exist anymore, so the README currently shows an error badge.
Maybe it would be possible to instead refer to the PR workflow, but (in case that works) it would then likely show the CI status of an arbitrary PR on the README, which is probably not useful. So removing the badge completely probably makes more sense.
> chore: remove outdated CI workflow badge from README

- selffuzz/src/test/java/com/code_intelligence/selffuzz/mutation/ArgumentsMutatorFuzzTest.java
- selffuzz/src/test/java/com/code_intelligence/selffuzz/mutation/BUILD.bazel
- selffuzz/src/test/java/com/code_intelligence/selffuzz/mutation/ImmutableBean.java
- src/main/java/com/code_intelligence/jazzer/mutation/combinator/InPlaceProductMutator.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/aggregate/CachedConstructorMutatorTest.java
The `InPlaceProductMutator` did not handle empty mutator lists in its `writeExclusive` implementation. Such a mutator is constructed for Beans with constructors that take no arguments.
If such a mutator was the last in the list of mutators this would lead to a `Index -1 out of bounds for length 0`.
> fix index out of bounds when mutating empty constructor arguments
