- README.md
> Add finding by @GanbaruTobi

- .github/workflows/run-all-tests.yml
- README.md
- driver/libfuzzer_callbacks.cpp
- examples/BUILD.bazel
- third_party/jni/BUILD.bazel
With the exception of the native and the fork test, everything seems to work fine on macOS 10.15 with this PR.
> Provide basic macOS compatibility

- README.md
- agent/src/main/java/com/code_intelligence/jazzer/api/Jazzer.java
- agent/src/main/java/com/code_intelligence/jazzer/runtime/HardToCatchThrowable.java
- agent/src/main/java/com/code_intelligence/jazzer/runtime/JazzerInternal.java
- driver/fuzz_target_runner.cpp
- driver/fuzz_target_runner.h
- driver/jvm_tooling.cpp
- driver/jvm_tooling.h
- examples/BUILD.bazel
- examples/src/main/java/com/example/ExamplePathTraversalFuzzer.java
- examples/src/main/java/com/example/ExamplePathTraversalFuzzerHooks.java
See the individual commit messages for details.
> Allow reliable finding reports from hooks

- driver/libfuzzer_callbacks.cpp
Jazzer currently segfaults in __sanitizer_weak_is_relevant_pc when it is
called from an intercepted memcmp on a non-main JVM thread. This hints
at a thread-safety issue since the vector with address ranges to ignore
can be read while it is being modified.
With this commit, reads to the vector only occur after all writes.
The segfault stack trace obtained from ClusterFuzz:
```
==613278==ERROR: AddressSanitizer: SEGV on unknown address 0x6060003a0000 (pc 0x0000004d1410 bp 0x7f0fcd4330a0 sp 0x7f0fcd4330a0 T12)
==613278==The signal is caused by a READ memory access.
INFO: libFuzzer ignores flags that start with '--'
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2232662950
SCARINESS: 20 (wild-addr-read)
INFO: Loaded 2 modules   (614 inline 8-bit counters): 512 …
```
> Speculative fix for crashes in intercepted memcmp

- bazel/fuzz_target_test_wrapper.sh
- driver/libfuzzer_driver.cpp
Also makes the tests look for a crash dump.
> Fix dump of crashing input on sanitizer report

- driver/fuzz_target_runner.cpp
This allows minimizing bugs further by ignoring stack trace changes.
> Optionally omit the DEDUP_TOKEN

- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/CoverageRecorder.kt
- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/EdgeCoverageInstrumentor.kt
- agent/src/test/java/com/code_intelligence/jazzer/instrumentor/CoverageInstrumentationTest.kt
- driver/coverage_tracker.cpp
- driver/coverage_tracker.h
- driver/fuzz_target_runner.cpp
- driver/libfuzzer_driver.cpp
- driver/libfuzzer_driver.h
- driver/sanitizer_symbols_for_tests.cpp
- repositories.bzl
- third_party/BUILD.bazel
- third_party/jacoco-make-probe-adapter-subclassable.patch
- third_party/libFuzzer-get-covered-pcs.patch
I will move the libFuzzer patch over to https://github.com/CodeIntelligenceTesting/llvm-project-jazzer after the review.
> Add option to generate coverage report

- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
The glob matching on class names to instrument introduced a dependency
on java.util.Regex, which results in two problems:
* Since the logic required to determine that java.util.Regex should not
be instrumented requires java.util.Regex, we obtain
ClassCircularityErrors. While harmless, they pollute the logs and
we don't have a good way to filter them out.
* Jazzer can't be used to fuzz java.util.Regex.
Since we don't need the full power of globs, this commit adds a very
simple glob matcher that only supports the cases foo.bar, foo.* and
foo.**.
> Remove dependency on java.util.Regex

- driver/jvm_tooling.cpp
If Jazzer is imported as an external workspace from another Bazel
workspace, the runfiles path of the agent is
../jazzer/agent/jazzer_agent_deploy.jar rather than
agent/jazzer_agent_deploy.jar. Since the first path applies more
generally, we switch to it, but perform a check for a Bazel env variable
to prevent loading agents from potentially untrusted sibling dirs.
> Fix Jazzer agent lookup

- agent/src/main/java/com/code_intelligence/jazzer/agent/CoverageIdStrategy.kt
Speculative fix for synchronization failures observed on ClusterFuzz.
> Close sync file instead of just releasing the lock

- agent/src/main/java/com/code_intelligence/jazzer/agent/CoverageIdStrategy.kt
This should help root cause the rare but persistent coverage ID sync
failures observed on ClusterFuzz.
> Add process UUID to coverage ID sync file

- .github/workflows/run-all-tests.yml
The *-latest GitHub Actions images include Bazelisk.
> Use preinstalled Bazelisk

- driver/jvm_tooling.cpp
https://docs.oracle.com/en/java/javase/11/gctuning/available-collectors.html#GUID-414C9D95-297E-4EE3-B0D9-36F158A83393
> Optimize GC for high throughput

- docker/build_all.sh
- docker/push_all.sh
Also make it possible to run the scripts from any directory.
> Add a script that updates and pushes all images

- agent/src/main/java/com/code_intelligence/jazzer/autofuzz/FuzzTarget.java
- agent/src/main/java/com/code_intelligence/jazzer/autofuzz/Meta.java
- agent/src/main/java/com/code_intelligence/jazzer/autofuzz/YourAverageJavaClass.java
- driver/fuzz_target_runner.cpp
Should address all comments from #205 except for https://github.com/CodeIntelligenceTesting/jazzer/pull/205#discussion_r731708065.
> Autofuzz review improvements

- agent/src/main/java/com/code_intelligence/jazzer/autofuzz/AutofuzzCodegenVisitor.java
- agent/src/main/java/com/code_intelligence/jazzer/autofuzz/FuzzTarget.java
- agent/src/main/java/com/code_intelligence/jazzer/autofuzz/Meta.java
- agent/src/test/java/com/code_intelligence/jazzer/autofuzz/BUILD.bazel
- agent/src/test/java/com/code_intelligence/jazzer/autofuzz/BuilderPatternTest.java
- agent/src/test/java/com/code_intelligence/jazzer/autofuzz/InterfaceCreationTest.java
- agent/src/test/java/com/code_intelligence/jazzer/autofuzz/MetaTest.java
- agent/src/test/java/com/code_intelligence/jazzer/autofuzz/SettersTest.java
- agent/src/test/java/com/code_intelligence/jazzer/autofuzz/TestHelpers.java
Nested builders, setters and Method/Constructor are not yet implemented.
> Implement code generation for consume and autofuzz

- README.md
> Document `--jvm_args` in the README

- examples/BUILD.bazel
- examples/src/main/java/com/example/JpegImageParserFuzzer.java
- repositories.bzl
Fixes https://github.com/google/oss-fuzz/issues/6926.
> Ensure that escapes are honored by fork and merge

- agent/src/main/java/com/code_intelligence/jazzer/instrumentor/CoverageRecorder.kt
- agent/src/main/java/com/code_intelligence/jazzer/runtime/CoverageMap.java
- driver/coverage_tracker.cpp
- driver/coverage_tracker.h
- driver/fuzz_target_runner.cpp
- driver/fuzzed_data_provider_test.cpp
- driver/jvm_tooling.cpp
- driver/jvm_tooling_test.cpp
This PR includes the final preparations to switch to a new CoverageMap implementation.
> Refactor CoverageMap

- bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java
Without this fallback, users can no longer pass in e.g. paths to corpus
directories into the examples supplied with Jazzer.
> Fall back to non-rlocation paths in FuzzTargetTestWrapper

- agent/src/main/java/com/code_intelligence/jazzer/api/Jazzer.java
This unlocks JIT optimizations.
> Make MethodHandles in Jazzer final

- driver/coverage_tracker.cpp
libFuzzer only checks the value of a PC when the corresponding flag is
not zero. Therefore, it is safe to set the whole PC-Table array to zero.
> Simplify registering PC tables

- driver/sanitizer_hooks_with_pc.cpp
Instead of running through 64 nops on average, every instruction in the
trampoline now jumps directly to the end of the function.
> Replace nop with ret sled on ARM64

- agent/src/main/java/com/code_intelligence/jazzer/runtime/CoverageMap.java
- agent/src/main/java/com/code_intelligence/jazzer/runtime/UnsafeProvider.java
- driver/coverage_tracker.cpp
- driver/coverage_tracker.h
- driver/sanitizer_hooks_with_pc.cpp
Few minor refactorings I did when going through the code during reviews
> Minor refactoring and cleanup

- agent/src/main/java/com/code_intelligence/jazzer/agent/CoverageIdStrategy.kt
- agent/src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
Relaxed visibility eases the usage of agent classes by third party software.
> Relax visibility of agent classes

- .bazelrc
See https://github.com/bazelbuild/bazel/issues/7849#issuecomment-1022932563.
> Fix JDK version specification for Maven publish

- docker/jazzer/Dockerfile
> Fix cifuzz/jazzer subprocess issue

- .github/workflows/run-all-tests.yml
- agent/src/main/native/com/code_intelligence/jazzer/runtime/jazzer_fuzzer_callbacks.cpp
- bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java
- driver/fuzz_target_runner.cpp
- driver/jvm_tooling.cpp
- tests/BUILD.bazel
- tests/src/test/java/com/example/JazzerApiFuzzer.java
Fixes https://github.com/google/oss-fuzz/issues/7507
> Add the agent to the classpath with --nohooks

- .github/workflows/oss-fuzz.yml
Issue https://github.com/actions/checkout/issues/760
> Workaround GitHub checkout action issue

- .bazelrc
- bazel/fuzz_target.bzl
- bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java
- driver/fuzz_target_runner.cpp
- tests/BUILD.bazel
- tests/src/test/java/com/example/MemoryLeakFuzzer.java
> Fix memory leaks in native code

- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/ExpressionLanguageInjection.kt
I added the support for org.apache.el.ExpressionFactoryImpl and jakarta.el.ExpressionFactory in Expression Language Injection Detector. With the modification we can catch Expression Language Injection within Tomcat Applications.
> Add support for Tomcat and Jakarta Expression Language Injection Bug Detectors.

- driver/src/main/java/com/code_intelligence/jazzer/driver/Driver.java
This is necessary for a pure Java driver as we can no longer set -Xmx in
that situation. It is also much cleaner than hand-tuning -Xmx, but we
still keep the max heap size in the native driver for backwards
compatibility with existing crashing inputs.
> driver: Set a default -rss_limit_mb

- driver/src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetRunner.java
- driver/src/main/java/com/code_intelligence/jazzer/driver/Opt.java
This ensures that the fuzz target is found even if Driver is loaded by
a custom class loader.
> driver: Load fuzz target with Driver's class loader 

- driver/src/main/java/com/code_intelligence/jazzer/autofuzz/AutofuzzCodegenVisitor.java
- driver/src/main/java/com/code_intelligence/jazzer/autofuzz/FuzzTarget.java
- driver/src/main/java/com/code_intelligence/jazzer/driver/ReproducerTemplate.java
- driver/src/test/java/com/code_intelligence/jazzer/autofuzz/AutofuzzCodegenVisitorTest.java
- driver/src/test/java/com/code_intelligence/jazzer/autofuzz/BUILD.bazel
- driver/src/test/java/com/code_intelligence/jazzer/autofuzz/MetaTest.java
> Fix Autofuzz codegen

- driver/src/main/java/com/code_intelligence/jazzer/autofuzz/FuzzTarget.java
- driver/src/main/java/com/code_intelligence/jazzer/autofuzz/Meta.java
- driver/src/test/java/com/code_intelligence/jazzer/autofuzz/BUILD.bazel
- driver/src/test/java/com/code_intelligence/jazzer/autofuzz/InterfaceCreationTest.java
- driver/src/test/java/com/code_intelligence/jazzer/autofuzz/MetaTest.java
Fixes https://github.com/CodeIntelligenceTesting/jazzer/issues/465
> autofuzz: Do not cast to non-public types

- driver/src/main/java/com/code_intelligence/jazzer/driver/FuzzTargetRunner.java
Motivated by https://github.com/CodeIntelligenceTesting/jazzer-clojure-example/issues/1
> driver: Improve fuzz test class not found error message

- driver/src/main/java/com/code_intelligence/jazzer/driver/BUILD.bazel
- driver/src/main/java/com/code_intelligence/jazzer/driver/Opt.java
> driver: Add --version flag

- .bazelrc
- BUILD.bazel
> bazel: Fix build on arm64 macOS without Rosetta

- docker/jazzer/Dockerfile
> docker: Add missing `jazzer_standalone.jar`

- .github/workflows/check-formatting.yml
- format.sh
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/Deserialization.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/ExpressionLanguageInjection.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/LdapInjection.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/NamingContextLookup.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/OsCommandInjection.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/ReflectiveCall.kt
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/RegexInjection.kt
- src/jmh/java/com/code_intelligence/jazzer/instrumentor/DirectByteBufferStrategy.kt
- src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
- src/main/java/com/code_intelligence/jazzer/agent/CoverageIdStrategy.kt
- src/main/java/com/code_intelligence/jazzer/agent/RuntimeInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/driver/ExceptionUtils.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/ClassInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/CoverageRecorder.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/DescriptorUtils.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/EdgeCoverageInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/Hook.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/HookInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/HookMethodVisitor.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/Hooks.kt
- src/main/java/com/code_intelligence/jazzer/instrumentor/TraceDataFlowInstrumentor.kt
- src/main/java/com/code_intelligence/jazzer/utils/ManifestUtils.kt
- src/main/java/com/code_intelligence/jazzer/utils/SimpleGlobMatcher.kt
- src/test/java/com/code_intelligence/jazzer/instrumentor/CoverageInstrumentationTest.kt
- src/test/java/com/code_intelligence/jazzer/instrumentor/DescriptorUtilsTest.kt
- src/test/java/com/code_intelligence/jazzer/instrumentor/PatchTestUtils.kt
- src/test/java/com/code_intelligence/jazzer/instrumentor/TraceDataFlowInstrumentationTest.kt
This PR updates the formatting tools and the corresponding comments in the docs.
> Update scripts and docs, and rerun the scripts

- src/main/java/com/code_intelligence/jazzer/autofuzz/FuzzTarget.java
- tests/BUILD.bazel
- tests/src/test/java/com/example/AutofuzzAssertionErrorTarget.java
> autofuzz: Enable assertions in Java reproducers

- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/LdapInjection.kt
> Fix typo in message

- sanitizers/sanitizers.bzl
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/BUILD.bazel
- sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/XPathInjection.kt
- sanitizers/src/test/java/com/example/BUILD.bazel
- sanitizers/src/test/java/com/example/XPathInjection.java
Added XPath Sanitizer + simple test case
> Xpath sanitizer

- src/main/java/com/code_intelligence/jazzer/agent/Agent.kt
Errors retransforming a class should not prevent Jazzer from starting. These classes are assumed to be not interesting nor important for the fuzzing run and can be safely ignored.
> agent: retry instrumentation on errors

- src/main/java/com/code_intelligence/jazzer/mutation/annotation/WithSize.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/BUILD.bazel
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/CollectionMutators.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/ListMutatorFactory.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/collection/MapMutatorFactory.java
- src/main/java/com/code_intelligence/jazzer/mutation/mutator/lang/StringMutatorFactory.java
- src/main/java/com/code_intelligence/jazzer/mutation/support/StreamSupport.java
- src/main/java/com/code_intelligence/jazzer/mutation/support/TypeSupport.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/StressTest.java
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/BUILD.bazel
- src/test/java/com/code_intelligence/jazzer/mutation/mutator/collection/MapMutatorTest.java
> mutator: Add map mutator

- src/main/java/com/code_intelligence/jazzer/junit/AgentConfigurator.java
This was added unintentionally in f0562981404fdda4816aa5f757eb58cc9bf2df16.
> junit: Remove unnecessary `setIfDefault`

- .github/workflows/fuzzing.yaml
- selffuzz/cifuzz.yaml
- selffuzz/src/test/java/com/code_intelligence/selffuzz/FuzzTestCase.java
Adds a (mostly) stock actions config and fixes the jazzer project name because the previous one was deleted.
> Add workflow to run fuzzing on PRs

- README.md
- src/main/java/com/code_intelligence/jazzer/junit/FuzzTest.java
> More clearly document that only a single fuzz test is fuzzed per run

- WORKSPACE.bazel
- tests/BUILD.bazel
> build: update toolchains_llvm dependency
